#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling, testing and building your project before committing'

#check prettier
npm run check-format ||
(
    echo 'Prettier check failed. Run npm run format, add changed and try commit again';
    false;
)

#check eslint
npm run check-lint ||
(
    echo 'ESLint check failed. Make the required changes listed above, add changes and try commit again';
    false;
)

#check tsconfig
npm run check-types ||
(
    echo 'Failed type check. Make the required changes listed above, add changes and try commit again';
    false;
)

npm run build ||
(
    echo 'Your build failed, view errors above';
    false;
)

echo 'Success Commit';